//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isolucion.PortalLicenciamiento.Api.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id_Cliente { get; set; }
        public string NomCliente { get; set; }
        public string Documento { get; set; }
        public string Licencia { get; set; }
        public System.DateTime InicioVigencia { get; set; }
        public System.DateTime FinVigencia { get; set; }
        public bool Activo { get; set; }
        public string ActualizacionStatusMensaje { get; set; }
    }
}
