//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isolucion.PortalLicenciamiento.Api.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componente
    {
        public int Id_Componente { get; set; }
        public string NomComponente { get; set; }
        public string Descripcion { get; set; }
        public int TipoComponente { get; set; }
        public string RutasRelativas { get; set; }
        public string Excepciones { get; set; }
        public string NombresSistema { get; set; }
        public string NombresAuxiliares { get; set; }
        public string NombresPool { get; set; }
        public string NombreArchivoZip { get; set; }
        public int Id_WebSite { get; set; }
    }
}
