//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isolucion.PortalLicenciamiento.Api.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionCliente
    {
        public int Id_InformacionCliente { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public string InformacionClienteDetalle { get; set; }
    }
}
