//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isolucion.PortalLicenciamiento.Api.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepositorioDbContext : DbContext
    {
        public RepositorioDbContext()
            : base("name=RepositorioDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<Componente> Componente { get; set; }
        public virtual DbSet<ActualizacionLog> ActualizacionLog { get; set; }
        public virtual DbSet<InformacionCliente> InformacionCliente { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
