//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isolucion.ServicioActualizacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBSITE
    {
        public short Id_WebSite { get; set; }
        public string WebSite1 { get; set; }
        public string RutaWebSite { get; set; }
        public string RutaArticulo { get; set; }
        public string RutaLibreria { get; set; }
        public string RutaHttpArticulo { get; set; }
        public string Email { get; set; }
        public string TipoSeguridad { get; set; }
        public string RutaPlugin { get; set; }
        public string RutaAnexo { get; set; }
        public string RutaHTTPAnexo { get; set; }
        public string NomWebSite { get; set; }
        public string RutaHttpServicios { get; set; }
        public bool RequiereActualizacion { get; set; }
        public string RutaDescarga { get; set; }
    }
}
